### ISSUE TITLE
Blockchain seems stuck on block 5362

### ISSUE THREAD

**Issue by oxhak** [alloy-project/alloy#8]
Blockchain seems stuck on block 5362 since hours, maybe related to the "Possible issue with timestamp verification for tx # 6" reported issue.

**Comment by alloy-project** [comment]
We’re still looking into this issue, it’s most likely caused by the recent hashrate spike. Everyone will be informed when an fix has been pushed to the repository.

**Comment by oxhak** [comment]
The discovery of new blocks works again, the blockchain of alloy undergoes attacks to generate infinite coins, but alloy is not affected by this bug and this attack only freezes the blockchain, the developers work already on a fix to bring to this issue, everyone should be informed as soon as the fix has been deployed.

**Comment by oxhak** [comment]
Despite the update, the old version is still problematic on the network, maybe a fork is needed to revole this issue to make the old one unusable ?

**Comment by oxhak** [comment]
I said that because popularpool was stuck but alloypool seems works fine, but it can still happen that a block takes an hour to be found randomly.

**Comment by kracharan** [comment]
Or started working for me again after deleting the block chain and pulling it in with the updated version.

**Comment by oxhak** [comment]
popularpool is not stuck, was just unlucky not finding a block for more than 3 hours.

**Comment by oxhak** [comment]
I have no issues with alloyd / simplewallet with the updated version.
